CC=gcc
OPTIONS=-Wall -g -O0 -D_GNU_SOURCE -DTEST_1xx -DTEST_1XX -DTESTER_1XX
LIBS=-lctester
LIBDIR=-L ~cis1xx/lib/ctester/ctester_v3/lib/
INCLUDEDIR=-I ~cis1xx/lib/ctester/ctester_v3/include/ -I /home1/e/ese116/submit/supple/

all:
	$(CC) $(OPTIONS) $(LIBDIR) $(INCLUDEDIR) hw01-tester.c hal.c ${LIBS} -o hw01-tester

clean:
	rm -f *.o hw01-tester

