CC=gcc
OPTIONS=-Wall -g -O0 -D_GNU_SOURCE -DTEST_1xx -DTEST_1XX -DTESTER_1XX
LIBS=-lctester
LIBDIR=-L ~cis1xx/lib/ctester/ctester_v3/lib/ 
INCLUDEDIR=-I ~cis1xx/lib/ctester/ctester_v3/src/ -I /home1/e/ese116/submit/supple/ -I /Users/lukecheng/Documents/Eclipse\ Workspace/ESE116GradingLibrary/ctester/ctester_v3/include


all:
	$(CC) $(OPTIONS) $(LIBDIR) $(INCLUDEDIR) hw05-tester.c tokenizer.c testGetChar.c testGetWord.c testSortAndDeleteDuplicates.c ${LIBS} -o hw05-tester

clean:
	rm -f *.o hw05-tester
