CC=gcc
OPTIONS=-Wall -g -O0 -D_GNU_SOURCE -DTEST_1xx -DTEST_1XX -DTESTER_1XX
LIBS=-lctester
LIBDIR=-L /home1/c/cse1xx/lib/ctester/robust/
INCLUDEDIR=-I /home1/c/cse1xx/lib/ctester/robust/ -I /home1/e/ese116/submit/supple/


all:    	
	$(CC) $(OPTIONS) $(LIBDIR) $(INCLUDEDIR) hw01-tester.c calc.c ${LIBS} -o hw01-tester

clean:
	rm -f *.o hw01-tester
